services:
  - type: web
    name: personal-library-scanner
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

    aptPackages:
      - tesseract-ocr
      - libzbar0
